from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from backend.api.services.session_store import SessionMeta


@runtime_checkable
class SessionStore(Protocol):
    def reset(self) -> None: ...

    def create_session(self, *, scene: str = "doctor", patient_id: int | None = None) -> SessionMeta: ...

    def get_session(self, session_id: str) -> SessionMeta | None: ...

    def find_uploaded_asset(self, session_id: str, asset_id: str) -> tuple[SessionMeta, dict[str, Any]] | None: ...

    def rotate_thread(self, session_id: str, *, clear_patient_id: bool = False) -> SessionMeta: ...

    def set_patient_id(
        self,
        session_id: str,
        patient_id: int | None,
        *,
        allow_replace: bool = False,
    ) -> SessionMeta: ...

    def bind_patient(self, session_id: str, patient_id: int) -> SessionMeta: ...

    def try_acquire_run_lock(self, session_id: str, run_id: str) -> bool: ...

    def release_run_lock(self, session_id: str, run_id: str) -> bool: ...

    def enqueue_context_message(self, session_id: str, message: Any) -> None: ...

    def drain_context_messages(self, session_id: str) -> list[Any]: ...

    def restore_context_messages(self, session_id: str, messages: list[Any]) -> None: ...

    def touch(self, session_id: str) -> None: ...

    def bump_snapshot_version(self, session_id: str) -> int: ...

    def set_context_maintenance(self, session_id: str, payload: dict[str, Any] | None) -> None: ...

    def set_patient_context_cache(self, session_id: str, cache: dict[str, Any]) -> None: ...

    def clear_legacy_medical_card(self, session_id: str) -> None: ...

    def merge_context_state(self, session_id: str, updates: dict[str, Any]) -> None: ...
